#!/usr/bin/env bash
# Configures an Ubuntu server with Nginx

# Update package list and install nginx
apt-get update -y
apt-get install nginx -y

# Create a simple HTML page with "Holberton School"
echo "Holberton School" > /var/www/html/index.html

# Ensure nginx is running
service nginx start
