#!/usr/bin/env bash
# Script that configures Nginx with a 301 redirect

# Update package list
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create the index page with required content
echo "Holberton School" > /var/www/html/index.html

# Add redirect rule to nginx config
sed -i '/server_name _;/a \\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Start nginx service (without systemctl)
service nginx restart
